In [3]:
#list的運算,需要利用迴圈
import random
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]

result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)

result


[142,
 161,
 126,
 152,
 180,
 149,
 161,
 179,
 133,
 160,
 129,
 135,
 179,
 137,
 127,
 162,
 159,
 156,
 145,
 167,
 153,
 148,
 141,
 172,
 157,
 163,
 151,
 167,
 161,
 162,
 153,
 162,
 186,
 159,
 186,
 163,
 155,
 174,
 139,
 153,
 143,
 156,
 153,
 146,
 160,
 158,
 160,
 190,
 174,
 186]

In [2]:
#使用numpy , 大量資料用陣列運算 速度會快很多 ndArray

import numpy as np
chinese = np.random.randint(60, high=100 , size=50)
english = np.random.randint(60, high=100 , size=50)
result = chinese + english
result

array([162, 155, 181, 141, 185, 178, 150, 170, 150, 169, 132, 172, 141,
       158, 172, 190, 148, 123, 164, 163, 148, 151, 152, 186, 194, 165,
       152, 179, 160, 143, 177, 187, 152, 143, 141, 151, 158, 161, 180,
       126, 141, 154, 152, 172, 138, 163, 158, 162, 147, 145])

In [10]:
#50個學生,5個分數
import numpy as np

students = np.random.randint(60,high=100,size=(50,5))
print(students)
sum = np.sum(students,axis=1)
average = np.average(students,axis=1)
print(sum)
print("============")
print(average)

[[92 67 63 63 73]
 [98 75 89 66 98]
 [93 74 92 80 99]
 [93 93 67 79 91]
 [83 87 73 65 81]
 [60 76 80 62 90]
 [86 68 93 70 73]
 [91 66 61 80 87]
 [69 90 75 86 61]
 [87 70 85 89 85]
 [99 94 77 95 92]
 [87 65 91 88 93]
 [94 96 89 88 82]
 [84 64 81 93 84]
 [95 82 75 90 60]
 [70 96 99 89 96]
 [61 74 99 94 91]
 [77 73 76 94 74]
 [61 66 85 78 88]
 [83 71 96 85 94]
 [99 85 68 92 62]
 [70 78 90 80 78]
 [71 78 94 82 73]
 [81 79 73 74 77]
 [77 64 64 68 67]
 [68 89 86 79 67]
 [87 98 70 93 83]
 [67 87 77 96 88]
 [61 61 73 94 73]
 [85 91 80 96 83]
 [60 65 75 73 69]
 [80 80 79 66 76]
 [93 99 95 92 73]
 [98 70 60 98 84]
 [83 67 84 98 70]
 [60 88 91 71 69]
 [67 60 63 81 76]
 [98 97 75 65 95]
 [73 88 84 71 64]
 [84 69 65 99 74]
 [90 72 69 77 85]
 [93 83 65 67 98]
 [65 98 70 63 81]
 [97 75 98 70 63]
 [93 84 95 87 64]
 [80 60 89 67 90]
 [99 82 84 94 62]
 [79 61 61 72 61]
 [95 82 80 74 60]
 [96 88 60 69 98]]
[358 426 438 423 389 368 390 385 381 416 457 424 449 406 402 450 419 394
 378 429 406 396 398 384 3