In [3]:
#list的運算,需要利用迴圈
import random
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]

result = []
for i in range(50):
    total = chinese[i] + english[i]
    result.append(total)

result


[142,
 161,
 126,
 152,
 180,
 149,
 161,
 179,
 133,
 160,
 129,
 135,
 179,
 137,
 127,
 162,
 159,
 156,
 145,
 167,
 153,
 148,
 141,
 172,
 157,
 163,
 151,
 167,
 161,
 162,
 153,
 162,
 186,
 159,
 186,
 163,
 155,
 174,
 139,
 153,
 143,
 156,
 153,
 146,
 160,
 158,
 160,
 190,
 174,
 186]

In [2]:
#使用numpy , 大量資料用陣列運算 速度會快很多 ndArray

import numpy as np
chinese = np.random.randint(60, high=100 , size=50)
english = np.random.randint(60, high=100 , size=50)
result = chinese + english
result

array([162, 155, 181, 141, 185, 178, 150, 170, 150, 169, 132, 172, 141,
       158, 172, 190, 148, 123, 164, 163, 148, 151, 152, 186, 194, 165,
       152, 179, 160, 143, 177, 187, 152, 143, 141, 151, 158, 161, 180,
       126, 141, 154, 152, 172, 138, 163, 158, 162, 147, 145])

In [12]:
#50個學生,5個分數
import numpy as np

students = np.random.randint(60,high=100,size=(50,5))
print(students)
sum = np.sum(students,axis=1)
average = np.average(students,axis=1)
print(sum)
print("============")
print(average)

[[72 77 73 62 79]
 [62 75 76 90 89]
 [62 71 91 68 95]
 [64 88 64 65 95]
 [99 62 83 88 68]
 [83 82 67 62 61]
 [67 85 64 86 60]
 [75 81 61 70 98]
 [87 64 91 60 81]
 [71 86 77 97 78]
 [98 77 67 91 67]
 [81 89 73 89 85]
 [68 91 86 82 60]
 [97 73 71 64 67]
 [64 84 94 94 74]
 [76 64 91 71 70]
 [60 68 64 74 74]
 [75 79 99 81 91]
 [63 73 61 70 81]
 [66 93 93 60 64]
 [99 64 70 69 91]
 [70 99 89 95 71]
 [80 76 64 70 85]
 [77 82 78 62 73]
 [90 68 70 77 64]
 [96 96 84 61 66]
 [70 74 90 95 67]
 [81 98 96 72 84]
 [61 66 97 78 79]
 [90 81 76 87 76]
 [69 79 98 98 84]
 [86 80 73 86 94]
 [60 71 72 96 84]
 [94 73 72 70 73]
 [77 65 87 74 87]
 [90 94 78 61 90]
 [90 62 81 95 65]
 [84 96 72 75 98]
 [78 83 71 64 64]
 [83 67 99 90 74]
 [77 74 71 65 64]
 [82 64 67 78 92]
 [82 93 71 93 62]
 [98 62 85 77 87]
 [66 85 82 86 72]
 [90 67 80 92 90]
 [84 91 68 93 98]
 [95 61 97 73 91]
 [76 65 69 70 79]
 [92 96 94 97 63]]
[363 392 387 376 400 355 362 385 383 409 400 417 387 372 410 372 340 425
 348 376 393 424 375 372 3

In [15]:
for i in range(50):
    print(students[i])

[72 77 73 62 79]
[62 75 76 90 89]
[62 71 91 68 95]
[64 88 64 65 95]
[99 62 83 88 68]
[83 82 67 62 61]
[67 85 64 86 60]
[75 81 61 70 98]
[87 64 91 60 81]
[71 86 77 97 78]
[98 77 67 91 67]
[81 89 73 89 85]
[68 91 86 82 60]
[97 73 71 64 67]
[64 84 94 94 74]
[76 64 91 71 70]
[60 68 64 74 74]
[75 79 99 81 91]
[63 73 61 70 81]
[66 93 93 60 64]
[99 64 70 69 91]
[70 99 89 95 71]
[80 76 64 70 85]
[77 82 78 62 73]
[90 68 70 77 64]
[96 96 84 61 66]
[70 74 90 95 67]
[81 98 96 72 84]
[61 66 97 78 79]
[90 81 76 87 76]
[69 79 98 98 84]
[86 80 73 86 94]
[60 71 72 96 84]
[94 73 72 70 73]
[77 65 87 74 87]
[90 94 78 61 90]
[90 62 81 95 65]
[84 96 72 75 98]
[78 83 71 64 64]
[83 67 99 90 74]
[77 74 71 65 64]
[82 64 67 78 92]
[82 93 71 93 62]
[98 62 85 77 87]
[66 85 82 86 72]
[90 67 80 92 90]
[84 91 68 93 98]
[95 61 97 73 91]
[76 65 69 70 79]
[92 96 94 97 63]


In [20]:
students.ndim , students.shape, students.size, students.dtype

(2, (50, 5), 250, dtype('int64'))

In [21]:
#建立ndarray
#將list轉為ndarray
list = [[1,2,3],[2,3,4]]
np.array(list)

array([[1, 2, 3],
       [2, 3, 4]])

In [23]:
#使用numpy random
np.random.randn(3,4) #第一維是3,第二維是4

array([[-0.31481166,  0.35380548,  0.39116275,  0.99181222],
       [-1.2563029 , -0.28627396,  1.02856534, -0.19010937],
       [-1.72781112, -0.8384501 ,  0.21662782,  0.01039593]])

In [26]:
#使用numpy 內建的funtion
np.zeros((2,3))

np.linspace(-3,3,num=50)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])